export const MARKETING_ACTIVITY_PLANNER = "Marketing Activity Planner";
export const VENDOR_ONBOARDING = "Vendor Onboarding";
export const MEDICAL_CLAIM = "Medical claim";

export const EVENT_PLANNING_CALENDAR = "Event Planning Calendar";

export const branchData = [
	{ branch_name: "Ahmedabad", branch_code: "AHM" },
	{ branch_name: "Aurangabad", branch_code: "AUR" },
	{ branch_name: "Bengaluru", branch_code: "BAN" },
	{ branch_name: "Bhubaneswar", branch_code: "BHU" },
	{ branch_name: "Chandigarh", branch_code: "CHA" },
	{ branch_name: "Chennai", branch_code: "CHE" },
	{ branch_name: "Cochin", branch_code: "COC" },
	{ branch_name: "Bengaluru-Corporate", branch_code: "COR" },
	{ branch_name: "Durgapur", branch_code: "DUR" },
	{ branch_name: "Goa", branch_code: "GOA" },
	{ branch_name: "Guwahati", branch_code: "GUW" },
	{ branch_name: "Hubli", branch_code: "HUB" },
	{ branch_name: "Hyderabad", branch_code: "HYD" },
	{ branch_name: "Indore", branch_code: "IND" },
	{ branch_name: "Jabalpur", branch_code: "JAB" },
	{ branch_name: "Jaipur", branch_code: "JAI" },
	{ branch_name: "Jamshedpur", branch_code: "JAM" },
	{ branch_name: "Kolkata", branch_code: "KOL" },
	{ branch_name: "Lucknow", branch_code: "LUC" },
	{ branch_name: "Madurai", branch_code: "MAD" },
	{ branch_name: "Mumbai", branch_code: "MUM" },
	{ branch_name: "Nagpur", branch_code: "NAG" },
	{ branch_name: "Nellore", branch_code: "NEL" },
	{ branch_name: "New Delhi", branch_code: "DEL" },
	{ branch_name: "Patna", branch_code: "PAT" },
	{ branch_name: "Pune", branch_code: "PUN" },
	{ branch_name: "Raipur", branch_code: "RAI" },
	{ branch_name: "Rajkot", branch_code: "RAJ" },
	{ branch_name: "Salem", branch_code: "SAL" },
	{ branch_name: "Udaipur", branch_code: "UDA" },
	{ branch_name: "Vijaywada", branch_code: "VIJ" },
	{ branch_name: "Jamshedpur Plant", branch_code: "JPL" },
	{ branch_name: "Dharwad Plant", branch_code: "DPL" },
	{ branch_name: "Kharagapur Plant", branch_code: "KPL" },
	{ branch_name: "Others", branch_code: "OTH" },
	{ branch_name: "Nepal", branch_code: "NEP" },
	{ branch_name: "Bhutan", branch_code: "BHT" },
	{ branch_name: "Bangladesh", branch_code: "BDH" },
	{ branch_name: "SriLanka", branch_code: "SRL" },
	{ branch_name: "Africa", branch_code: "AFR" },
];

export const eventNameData = [
	{ title: "Customer Meet - Big (Above 50+ customers)" },
	{ title: "Customer Meet -Small" },
	{ title: "KA Customer meet" },
	{ title: "Application Study" },
	{ title: "Roadshow" },
	{ title: "Demo-in-Dirt" },
	{ title: "Try & Buy offer for Machines" },
	{ title: "Presentation to Govt. Bodies & Municipalities" },
	{ title: "Financier Meet" },
	{ title: "Customer Plant visit" },
	{ title: "Loan Mela" },
	{ title: "Product Launch" },
	{ title: "Newspaper Advt." },
	{ title: "Exhibitions & Fairs" },
	{ title: "Hoardings/Glow Sign Boards" },
	{ title: "Others-Sales" },
	{ title: "Operator Training" },
	{ title: "Operator Meet" },
	{ title: "Training to Customer Staff" },
	{ title: "Service Campaign" },
	{ title: "Competition Product Performance-Service" },
	{ title: "Others-Service" },
	{ title: "Parts Mela" },
	{ title: "Try & Buy offer for attachments" },
	{ title: "Others-Spares" },
	{ title: "Key Handing Over" },
	{ title: "Marketing HO Expense" },
];

export const regionData = [
	{ region_name: "East", region_code: "EAS" },
	{ region_name: "Central", region_code: "CEN" },
	{ region_name: "North", region_code: "NOR" },
	{ region_name: "South-1", region_code: "SO1" },
	{ region_name: "South-2", region_code: "SO2" },
	{ region_name: "West", region_code: "WES" },
	{ region_name: "Exports", region_code: "EXP" },
	{ region_name: "Corporate", region_code: "COR" },
];

export const budgetCodeData = [
	{
		fiscal_year: "2025-2026",
		code: "P1SMN1380105",
		id_desc: "North 1",
		value: 3800000,
	},
	{
		fiscal_year: "2025-2026",
		code: "P1SMN2380105",
		id_desc: "North 2",
		value: 3800000,
	},
	{
		fiscal_year: "2025-2026",
		code: "P1SME1380105",
		id_desc: "East 1",
		value: 4000000,
	},
	{
		fiscal_year: "2025-2026",
		code: "P1SME2380105",
		id_desc: "East 2",
		value: 1000000,
	},
	{
		fiscal_year: "2025-2026",
		code: "P1SMCR380105",
		id_desc: "Central",
		value: 3500000,
	},
	{
		fiscal_year: "2025-2026",
		code: "P1SMS1380105",
		id_desc: "South 1",
		value: 5000000,
	},
	{
		fiscal_year: "2025-2026",
		code: "P1SMS2380105",
		id_desc: "South 2",
		value: 3000000,
	},
	{
		fiscal_year: "2025-2026",
		code: "P1SMS3380105",
		id_desc: "South 3",
		value: 2300000,
	},
	{
		fiscal_year: "2025-2026",
		code: "P1SMW1380105",
		id_desc: "West 1",
		value: 4500000,
	},
	{
		fiscal_year: "2025-2026",
		code: "P1SMW2380105",
		id_desc: "West 2",
		value: 2500000,
	},
	{
		fiscal_year: "2025-2026",
		code: "U13406380105",
		id_desc: "KA Customer Engagement",
		value: 3500000,
	},
	{
		fiscal_year: "2025-2026",
		code: "U33406380105",
		id_desc: "Mining Customer Engagement",
		value: 4000000,
	},
	{
		fiscal_year: "2025-2026",
		code: "P33406380105",
		id_desc: "Product Launch & Small Exhibitions",
		value: 4000000,
	},
	{
		fiscal_year: "2025-2026",
		code: "P53406380105",
		id_desc: "Market Research",
		value: 700000,
	},
	{
		fiscal_year: "2025-2026",
		code: "U53406380105",
		id_desc: "Product Marketing",
		value: 1600000,
	},
	{
		fiscal_year: "2025-2026",
		code: "P63406380105",
		id_desc: "Product & Content Development",
		value: 5000000,
	},
	{
		fiscal_year: "2025-2026",
		code: "P73406380105",
		id_desc: "Retainers",
		value: 9400000,
	},
	{
		fiscal_year: "2025-2026",
		code: "P83406380105",
		id_desc: "Digital Marketing",
		value: 6800000,
	},
	{
		fiscal_year: "2025-2026",
		code: "U23406380105",
		id_desc: "Export Market Promotion",
		value: 1500000,
	},
	{
		fiscal_year: "2025-2026",
		code: "U33406380105",
		id_desc: "Corporate Communications",
		value: 4000000,
	},
];

export const verticalsData = [
	{
		departmentName: "Marketing",
		verticals: [
			"Product Marketing",
			"Branding and Communication",
			"Digital Communication",
			"Product Demonstrations",
			"Market Research",
		],
	},
	{
		departmentName: "Sales",
		verticals: [
			"Mining",
			"Infra/Construction",
			"Compact",
			"Rental",
			"Dealer Development",
			"key Accounts",
			"Sales Administration",
			"Used Equipments",
			"Exports",
			"Government Business",
		],
	},
	{
		departmentName: "Service",
		verticals: [
			"Infra/Construction",
			"FMC- Infra/Construction",
			"Technical Support Group",
			"Technical Training",
			"Training Academy",
			"Mining Service",
			"FMC-Mining",
			"Reman",
		],
	},
	{
		departmentName: "Manufacturing & Plant Administration",
		verticals: ["Dharwad", "Kharagpur"],
	},
	{
		departmentName: "Corporate",
		verticals: ["Managing Director's Office", "External Affairs"],
	},
	{
		departmentName: "Parts",
		verticals: [],
	},
];

export const products = [
	// ── Artworks (CRF) ──────────────────────────────────────────────────────
	{
		partNumber: "CRF-ART-001",
		name: "Backdrop",
		unitRate: null,
		productType: "CRF",
		category: "ARTWORK",
	},
	{
		partNumber: "CRF-ART-002",
		name: "Banner",
		unitRate: null,
		productType: "CRF",
		category: "ARTWORK",
	},
	{
		partNumber: "CRF-ART-003",
		name: "Standee",
		unitRate: null,
		productType: "CRF",
		category: "ARTWORK",
	},
	{
		partNumber: "CRF-ART-004",
		name: "Invitation",
		unitRate: null,
		productType: "CRF",
		category: "ARTWORK",
	},
	{
		partNumber: "CRF-ART-005",
		name: "Certificate",
		unitRate: null,
		productType: "CRF",
		category: "ARTWORK",
	},
	{
		partNumber: "CRF-ART-006",
		name: "Photo Frame",
		unitRate: null,
		productType: "CRF",
		category: "ARTWORK",
	},
	{
		partNumber: "CRF-ART-007",
		name: "Specification Board",
		unitRate: null,
		productType: "CRF",
		category: "ARTWORK",
	},
	{
		partNumber: "CRF-ART-008",
		name: "Registration Desk",
		unitRate: null,
		productType: "CRF",
		category: "ARTWORK",
	},
	{
		partNumber: "CRF-ART-009",
		name: "Podium",
		unitRate: null,
		productType: "CRF",
		category: "ARTWORK",
	},
	{
		partNumber: "CRF-ART-010",
		name: "Others (Artwork)",
		unitRate: null,
		productType: "CRF",
		category: "ARTWORK",
	},

	// ── Printed Materials (CRF) ─────────────────────────────────────────────
	{
		partNumber: "CRF-PM-001",
		name: "Catalogue ZX20U-5A 12 Pages",
		unitRate: 16.25,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-002",
		name: "Catalogue TMX20 4 Pages",
		unitRate: 11.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-003",
		name: "Catalogue ZX33U 4 Pages",
		unitRate: 11.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-004",
		name: "Catalogue EX200 Super Plus 4 Pages",
		unitRate: 11.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-005",
		name: "Catalogue EX210 Super Plus 4 Pages",
		unitRate: 11.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-006",
		name: "Catalogue ZX140H Multipage 20 Pages",
		unitRate: 33.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-007",
		name: "Catalogue ZX220 I 16 Pages",
		unitRate: 27.6,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-008",
		name: "Catalogue ZX220M 4 Pages",
		unitRate: 11.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-009",
		name: "Catalogue Insite 4 Pages",
		unitRate: 11.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-010",
		name: "Catalogue Shinrai BX80 6 Pages",
		unitRate: 11.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-011",
		name: "Catalogue TL340H Multipage 12 Pages",
		unitRate: 16.25,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-012",
		name: "Catalogue Quick Coupler 4 Pages",
		unitRate: 11.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-013",
		name: "Catalogue ZX33U 4 Pages (Alt)",
		unitRate: 11.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-014",
		name: "Catalogue ZX80 Multipage 16 Pages",
		unitRate: 27.6,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-015",
		name: "Catalogue ZX140H Multipage 20 Pages (Alt)",
		unitRate: 33.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-016",
		name: "Catalogue ZX370LCH Multipage 20 Pages",
		unitRate: 33.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-017",
		name: "Catalogue A Range of Attachment Multipage 20 Pages",
		unitRate: 33.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-018",
		name: "Catalogue NPK Rock Breaker 6 Pages",
		unitRate: 11.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-019",
		name: "Catalogue Consite Multipage 8 Pages",
		unitRate: 14.1,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-020",
		name: "Catalogue ZX650 16 Pages",
		unitRate: 27.6,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-021",
		name: "Catalogue EX70 4 Pages",
		unitRate: 11.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-022",
		name: "Catalogue EX130 4 Pages",
		unitRate: 11.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-023",
		name: "Catalogue Alicon Series 6 Pages",
		unitRate: 11.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-024",
		name: "Catalogue TG160 Motor Grader 4 Pages",
		unitRate: 11.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-025",
		name: "Catalogue TH76 8 Pages",
		unitRate: 14.1,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-026",
		name: "Catalogue ZX20U 12 Pages",
		unitRate: 16.25,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-027",
		name: "Catalogue ZX470 20 Pages",
		unitRate: 33.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-028",
		name: "Catalogue Product Portfolio 8 Pages",
		unitRate: 14.1,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-029",
		name: "Catalogue Alicon Super Series B145/B215/B235 2 Pages",
		unitRate: 9.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-030",
		name: "Catalogue Company Profile Multipage 20 Pages",
		unitRate: 120.0,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-031",
		name: "Catalogue ZX400 4 Pages",
		unitRate: 11.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-032",
		name: "Catalogue ZX400 20 Pages",
		unitRate: 33.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-033",
		name: "Catalogue Smart Cities 4 Pages",
		unitRate: 11.5,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-034",
		name: "Symbolic Keys",
		unitRate: 2800.0,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-035",
		name: "Invitation",
		unitRate: 40.0,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-036",
		name: "Regular Plaque",
		unitRate: 1250.0,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-037",
		name: "Oval Silver Coated Plaque",
		unitRate: 5500.0,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},
	{
		partNumber: "CRF-PM-038",
		name: "Others (Printed Material)",
		unitRate: null,
		productType: "CRF",
		category: "PRINTED_MATERIAL",
	},

	// ── Souvenirs (CRF) ─────────────────────────────────────────────────────
	{
		partNumber: "CRF-SV-001",
		name: "Operator T-Shirt",
		unitRate: 180.0,
		productType: "CRF",
		category: "SOUVENIR",
	},
	{
		partNumber: "CRF-SV-002",
		name: "Executive T-Shirt Regular",
		unitRate: 280.0,
		productType: "CRF",
		category: "SOUVENIR",
	},
	{
		partNumber: "CRF-SV-003",
		name: "Cap",
		unitRate: 70.0,
		productType: "CRF",
		category: "SOUVENIR",
	},
	{
		partNumber: "CRF-SV-004",
		name: "Coffee Mug",
		unitRate: 180.0,
		productType: "CRF",
		category: "SOUVENIR",
	},
	{
		partNumber: "CRF-SV-005",
		name: "Pierre Cardin Pen",
		unitRate: 110.0,
		productType: "CRF",
		category: "SOUVENIR",
	},
	{
		partNumber: "CRF-SV-006",
		name: "Regular Pen",
		unitRate: 20.0,
		productType: "CRF",
		category: "SOUVENIR",
	},
	{
		partNumber: "CRF-SV-007",
		name: "Key Chain",
		unitRate: 20.0,
		productType: "CRF",
		category: "SOUVENIR",
	},
	{
		partNumber: "CRF-SV-008",
		name: "Carry Bag",
		unitRate: 40.0,
		productType: "CRF",
		category: "SOUVENIR",
	},
	{
		partNumber: "CRF-SV-009",
		name: "Office Essentials Gift Set",
		unitRate: 300.0,
		productType: "CRF",
		category: "SOUVENIR",
	},
	{
		partNumber: "CRF-SV-010",
		name: "Wall Clock",
		unitRate: 725.0,
		productType: "CRF",
		category: "SOUVENIR",
	},
	{
		partNumber: "CRF-SV-011",
		name: "SHINRAI Umbrella",
		unitRate: 240.0,
		productType: "CRF",
		category: "SOUVENIR",
	},
	{
		partNumber: "CRF-SV-012",
		name: "SHINRAI Table Clock",
		unitRate: 200.0,
		productType: "CRF",
		category: "SOUVENIR",
	},
	{
		partNumber: "CRF-SV-013",
		name: "SHINRAI Mobile Stand",
		unitRate: 440.0,
		productType: "CRF",
		category: "SOUVENIR",
	},
	{
		partNumber: "CRF-SV-014",
		name: "SHINRAI T-Shirt",
		unitRate: 300.0,
		productType: "CRF",
		category: "SOUVENIR",
	},
	{
		partNumber: "CRF-SV-015",
		name: "SHINRAI Cap",
		unitRate: 80.0,
		productType: "CRF",
		category: "SOUVENIR",
	},
	{
		partNumber: "CRF-SV-016",
		name: "Wheel Loader Pen Stand",
		unitRate: 310.0,
		productType: "CRF",
		category: "SOUVENIR",
	},

	// ── Event Cost Overhead (EPF) ────────────────────────────────────────────
	{
		partNumber: "EPF-ECO-001",
		name: "Sponsorship",
		unitRate: null,
		productType: "EPF",
		category: "EVENT_OVERHEAD",
	},
	{
		partNumber: "EPF-ECO-002",
		name: "Space Rental",
		unitRate: null,
		productType: "EPF",
		category: "EVENT_OVERHEAD",
	},
	{
		partNumber: "EPF-ECO-003",
		name: "Invitation Printing",
		unitRate: null,
		productType: "EPF",
		category: "EVENT_OVERHEAD",
	},
	{
		partNumber: "EPF-ECO-004",
		name: "Stage Setup, Decor, Fabrication",
		unitRate: null,
		productType: "EPF",
		category: "EVENT_OVERHEAD",
	},
	{
		partNumber: "EPF-ECO-005",
		name: "Backdrop, Banners, Standees, Others",
		unitRate: null,
		productType: "EPF",
		category: "EVENT_OVERHEAD",
	},
	{
		partNumber: "EPF-ECO-006",
		name: "Sound / Display / Electrical System",
		unitRate: null,
		productType: "EPF",
		category: "EVENT_OVERHEAD",
	},
	{
		partNumber: "EPF-ECO-007",
		name: "Photography / Videography / Film Edit",
		unitRate: null,
		productType: "EPF",
		category: "EVENT_OVERHEAD",
	},
	{
		partNumber: "EPF-ECO-008",
		name: "Event Services",
		unitRate: null,
		productType: "EPF",
		category: "EVENT_OVERHEAD",
	},
	{
		partNumber: "EPF-ECO-009",
		name: "Snacks / Beverage",
		unitRate: null,
		productType: "EPF",
		category: "EVENT_OVERHEAD",
	},
	{
		partNumber: "EPF-ECO-010",
		name: "Lunch / Dinner / Others",
		unitRate: null,
		productType: "EPF",
		category: "EVENT_OVERHEAD",
	},
	{
		partNumber: "EPF-ECO-011",
		name: "Machine / Parts / Attachment Transportation",
		unitRate: null,
		productType: "EPF",
		category: "EVENT_OVERHEAD",
	},
	{
		partNumber: "EPF-ECO-012",
		name: "Diesel Expenses",
		unitRate: null,
		productType: "EPF",
		category: "EVENT_OVERHEAD",
	},
	{
		partNumber: "EPF-ECO-013",
		name: "Operator / Cleaner Charges",
		unitRate: null,
		productType: "EPF",
		category: "EVENT_OVERHEAD",
	},
	{
		partNumber: "EPF-ECO-014",
		name: "Souvenirs (Additional)",
		unitRate: null,
		productType: "EPF",
		category: "EVENT_OVERHEAD",
	},
	{
		partNumber: "EPF-ECO-015",
		name: "Miscellaneous Expenses",
		unitRate: null,
		productType: "EPF",
		category: "EVENT_OVERHEAD",
	},
];

// ─────────────────────────────────────────────────────────────────────────
// Static seed user definitions.
//
// Each entry is keyed by a name-based identifier (e.g. "syedFazal") so
// downstream seed logic can reference `usersByKey.syedFazal.id` instead of
// magic array indices like `users[6]`. Edit names/emails/phones freely —
// the `profiles` array is what actually drives permission assignment.
// ─────────────────────────────────────────────────────────────────────────

export const PROFILE_NAMES = {
	WORKSPACE_ADMIN: "Workspace Admin",
	MAP_ADMIN: "MAP Admin",
	VENDOR_ONBOARDING_ADMIN: "Vendor Onboarding Admin",
	FIELD_ENGINEER: "Field Engineer",
	EPC_SPECIALIST: "EPC Specialist",
	VENDOR_ONBOARDING_MANAGER: "Vendor Onboarding Manager",
	READ_ONLY: "Read-Only User",
} as const;

export type ProfileName = (typeof PROFILE_NAMES)[keyof typeof PROFILE_NAMES];

export interface SeedUserDefinition {
	key: string;
	first_name: string;
	last_name: string;
	email: string;
	phone_number: string;
	password: string;
	isSuperAdmin: boolean;
	profiles: ProfileName[];
}

const DEFAULT_PASSWORD = "Password@123";

export const seedUsers: SeedUserDefinition[] = [
	// ── Super Admin (1) ───────────────────────────────────────────────────
	{
		key: "syedFazal",
		first_name: "Syed",
		last_name: "Fazal",
		email: "syed.fazal@tatahitachi.com",
		phone_number: "9876500001",
		password: DEFAULT_PASSWORD,
		isSuperAdmin: true,
		profiles: [PROFILE_NAMES.WORKSPACE_ADMIN],
	},

	// ── Admin, both apps, not super (1) ───────────────────────────────────
	{
		key: "monica",
		first_name: "hepsiba",
		last_name: "monica",
		email: "hepsiba.monica@tatahitachi.com",
		phone_number: "9876500002",
		password: DEFAULT_PASSWORD,
		isSuperAdmin: true,
		profiles: [PROFILE_NAMES.WORKSPACE_ADMIN],
	},

	// ── App Admins: write in own app, read in the other (2) ───────────────
	{
		key: "siddharth",
		first_name: "siddharth",
		last_name: "chaturvedi",
		email: "siddharth.chaturvedi@tatahitachi.com",
		phone_number: "9876500016",
		password: DEFAULT_PASSWORD,
		isSuperAdmin: false,
		profiles: [PROFILE_NAMES.MAP_ADMIN],
	},
	{
		key: "rehna",
		first_name: "rehan",
		last_name: "nusrat",
		email: "rehan.nusrat@tatahitachi.com",
		phone_number: "9876500017",
		password: DEFAULT_PASSWORD,
		isSuperAdmin: false,
		profiles: [PROFILE_NAMES.VENDOR_ONBOARDING_ADMIN],
	},

	// ── Field Engineers (4) ────────────────────────────────────────────────
	{
		key: "vijay",
		first_name: "vijay",
		last_name: "parmar",
		email: "vijay.parmar@tatahitachi.com",
		phone_number: "9876500003",
		password: DEFAULT_PASSWORD,
		isSuperAdmin: false,
		profiles: [PROFILE_NAMES.FIELD_ENGINEER],
	},
	{
		key: "guruprasad",
		first_name: "guruprasad",
		last_name: "h",
		email: "guruprasad.h@tatahitachi.com",
		phone_number: "9876500004",
		password: DEFAULT_PASSWORD,
		isSuperAdmin: false,
		profiles: [PROFILE_NAMES.FIELD_ENGINEER],
	},
	{
		key: "girish",
		first_name: "girish",
		last_name: "kolambe",
		email: "girish.kolambe@tatahitachi.com",
		phone_number: "9876500005",
		password: DEFAULT_PASSWORD,
		isSuperAdmin: false,
		profiles: [PROFILE_NAMES.FIELD_ENGINEER],
	},
	{
		key: "shiva",
		first_name: "shiva",
		last_name: "rao",
		email: "shiva.rao@tatahitachi.com",
		phone_number: "9876500006",
		password: DEFAULT_PASSWORD,
		isSuperAdmin: false,
		profiles: [PROFILE_NAMES.FIELD_ENGINEER],
	},

	// ── EPC Specialists (2) ────────────────────────────────────────────────
	{
		key: "aswin",
		first_name: "aswin",
		last_name: "peranna",
		email: "aswin.peranna@tatahitachi.com",
		phone_number: "9876500007",
		password: DEFAULT_PASSWORD,
		isSuperAdmin: false,
		profiles: [PROFILE_NAMES.EPC_SPECIALIST],
	},
	{
		key: "harsimar",
		first_name: "harsimarpreet",
		last_name: "kaur",
		email: "harsimarpreet.kaur@tatahitachi.com",
		phone_number: "9876500008",
		password: DEFAULT_PASSWORD,
		isSuperAdmin: false,
		profiles: [PROFILE_NAMES.EPC_SPECIALIST],
	},

	// ── Vendor Onboarding Managers (3) ─────────────────────────────────────
	{
		key: "ashok",
		first_name: "ashok",
		last_name: "goenka",
		email: "ashok.goenka@tatahitachi.com",
		phone_number: "9876500009",
		password: DEFAULT_PASSWORD,
		isSuperAdmin: false,
		profiles: [PROFILE_NAMES.VENDOR_ONBOARDING_MANAGER],
	},
	{
		key: "anita",
		first_name: "anita",
		last_name: "sahoo",
		email: "anita.sahoo@tatahitachi.com",
		phone_number: "9876500010",
		password: DEFAULT_PASSWORD,
		isSuperAdmin: false,
		profiles: [PROFILE_NAMES.VENDOR_ONBOARDING_MANAGER],
	},
	{
		key: "sukumar",
		first_name: "sukumar",
		last_name: "Desai",
		email: "sukumar.desai@tatahitachi.com",
		phone_number: "9876500011",
		password: DEFAULT_PASSWORD,
		isSuperAdmin: false,
		profiles: [PROFILE_NAMES.VENDOR_ONBOARDING_MANAGER],
	},

	// ── Dual role: Field Engineer + Vendor Onboarding Manager (1) ─────────
	{
		key: "hemadri",
		first_name: "hemadri",
		last_name: "kurukotti",
		email: "hemadri.kurukotti@tatahitachi.com",
		phone_number: "9876500012",
		password: DEFAULT_PASSWORD,
		isSuperAdmin: false,
		profiles: [
			PROFILE_NAMES.FIELD_ENGINEER,
			PROFILE_NAMES.VENDOR_ONBOARDING_MANAGER,
		],
	},

	// ── Read-Only (3) ────────────────────────────────────────────────────
	{
		key: "nilanjan",
		first_name: "Nilanjan",
		last_name: "Das",
		email: "nilanjan.das@tatahitachi.com",
		phone_number: "9876500013",
		password: DEFAULT_PASSWORD,
		isSuperAdmin: false,
		profiles: [PROFILE_NAMES.READ_ONLY],
	},
	{
		key: "amit",
		first_name: "amit",
		last_name: "biswas",
		email: "amit.biswas@tatahitachi.com",
		phone_number: "9876500014",
		password: DEFAULT_PASSWORD,
		isSuperAdmin: false,
		profiles: [PROFILE_NAMES.READ_ONLY],
	},
	{
		key: "jitesh",
		first_name: "jitesh",
		last_name: "jittu",
		email: "jitesh.jittu@tatahitachi.com",
		phone_number: "9876500015",
		password: DEFAULT_PASSWORD,
		isSuperAdmin: false,
		profiles: [PROFILE_NAMES.READ_ONLY],
	},
];
