-- DropForeignKey
ALTER TABLE "CRF" DROP CONSTRAINT "CRF_epcId_fkey";

-- DropForeignKey
ALTER TABLE "EPF" DROP CONSTRAINT "EPF_epcId_fkey";

-- AddForeignKey
ALTER TABLE "EPF" ADD CONSTRAINT "EPF_epcId_fkey" FOREIGN KEY ("epcId") REFERENCES "EventProposal"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CRF" ADD CONSTRAINT "CRF_epcId_fkey" FOREIGN KEY ("epcId") REFERENCES "EventProposal"("id") ON DELETE CASCADE ON UPDATE CASCADE;
