import { Request, Response, NextFunction } from "express";
import bcrypt from "bcrypt";

import { prisma } from "@shared/config/prisma";
import ApiError from "@shared/utils/apiError";

import { checkOtpLimit, updateOtpLimit } from "@auth/otpRateLimiter";
import { signGuestAccessToken } from "./guest.auth";
import { OtpService } from "@auth/otp.services";

const otpService = new OtpService();

// ── Mobile + OTP ─────────────────────────────────────────────────────────
// Same OtpService (MSG91) staff login already uses — no separate guest
// OTP mechanism, just a different identity (Guest, not User) on either
// side of it.

export const sendGuestOtp = async (
  req: Request,
  res: Response,
  next: NextFunction,
) => {
  try {
    const { mobile } = req.body;
    if (!mobile) throw new ApiError(400, "Mobile number is required");

    const guest = await prisma.guest.findUnique({ where: { mobile } });
    if (!guest) {
      throw new ApiError(
        404,
        "No submissions found for this mobile number yet",
      );
    }

    const limit = await checkOtpLimit(mobile);
    if (!limit.allowed) {
      throw new ApiError(429, limit.message || "Failed to send OTP");
    }

    const data = await otpService.sendOtp(mobile);
    if (data.type === "error") {
      throw new ApiError(401, data.message || "Failed to send OTP");
    }

    await updateOtpLimit(mobile);

    res.status(200).json({ success: true, message: "OTP sent successfully" });
  } catch (error) {
    next(error);
  }
};

export const verifyGuestOtp = async (
  req: Request,
  res: Response,
  next: NextFunction,
) => {
  try {
    const { mobile, otp } = req.body;
    if (!mobile || !otp) {
      throw new ApiError(400, "Mobile number and OTP are required");
    }

    const otpResult = await otpService.verifyOtp(mobile, otp);
    if (otpResult.type !== "success") {
      throw new ApiError(400, otpResult.message || "Invalid or expired OTP");
    }

    const guest = await prisma.guest.findUnique({ where: { mobile } });
    if (!guest) {
      throw new ApiError(
        404,
        "No submissions found for this mobile number yet",
      );
    }

    const accessToken = signGuestAccessToken(guest.id);

    res.status(200).json({
      success: true,
      message: "Login successful",
      accessToken,
      guest: { id: guest.id, mobile: guest.mobile, email: guest.email },
    });
  } catch (error) {
    next(error);
  }
};

// ── Email + Password ─────────────────────────────────────────────────────
// Password is autogenerated at Guest creation (Pass 2/4) and emailed once —
// a guest never sets or resets it themselves. No forgot-password flow yet;
// if lost, credentials must be re-issued (open item, see prior discussion).

export const loginGuestWithPassword = async (
  req: Request,
  res: Response,
  next: NextFunction,
) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) {
      throw new ApiError(400, "Email and password are required");
    }

    const guest = await prisma.guest.findUnique({ where: { email } });
    if (!guest || !guest.password) {
      throw new ApiError(401, "Invalid credentials");
    }

    const isValidPassword = await bcrypt.compare(password, guest.password);
    if (!isValidPassword) {
      throw new ApiError(401, "Invalid credentials");
    }

    const accessToken = signGuestAccessToken(guest.id);

    res.status(200).json({
      success: true,
      message: "Login successful",
      accessToken,
      guest: { id: guest.id, mobile: guest.mobile, email: guest.email },
    });
  } catch (error) {
    next(error);
  }
};
